;;;; Generated from interop/interop.proto

;;;; Generated by ag-proto-cli vv1.0.0+dirty

(in-package "COMMON-LISP-USER")


(PROGN (DEFCONSTANT +PAYLOADTYPE-COMPRESSABLE+ 0))


(DEFCLASS EMPTY (AG-PROTO:PROTO-MESSAGE) NIL
          (:DOCUMENTATION "Proto message: Empty"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES ((AG-PROTO::OBJ EMPTY))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES ((TYPE (EQL 'EMPTY)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'EMPTY))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS PAYLOAD (AG-PROTO:PROTO-MESSAGE)
          ((TYPE :INITARG :TYPE :ACCESSOR PROTO-TYPE :INITFORM NIL :TYPE T)
           (BODY :INITARG :BODY :ACCESSOR BODY :INITFORM #() :TYPE
            (VECTOR (UNSIGNED-BYTE 8))))
          (:DOCUMENTATION "Proto message: Payload"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES ((AG-PROTO::OBJ PAYLOAD))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'TYPE)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 1 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'BODY)))
      (WHEN (AND AG-PROTO::VALUE (PLUSP (LENGTH AG-PROTO::VALUE)))
        (AG-PROTO::WRITE-FIELD-TAG 2 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED AG-PROTO::VALUE AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'PAYLOAD)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'PAYLOAD))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'TYPE)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOADTYPE
                                                             AG-PROTO::DATA))))
                 (2
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'BODY)
                          (AG-PROTO::READ-LENGTH-DELIMITED AG-PROTO::BUFFER)))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS ECHOSTATUS (AG-PROTO:PROTO-MESSAGE)
          ((CODE :INITARG :CODE :ACCESSOR CODE :INITFORM 0 :TYPE
            (SIGNED-BYTE 32))
           (MESSAGE :INITARG :MESSAGE :ACCESSOR MESSAGE :INITFORM "" :TYPE
            STRING))
          (:DOCUMENTATION "Proto message: EchoStatus"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES ((AG-PROTO::OBJ ECHOSTATUS))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'CODE)))
      (WHEN (AND AG-PROTO::VALUE (NOT (EQL AG-PROTO::VALUE 0)))
        (AG-PROTO::WRITE-FIELD-TAG 1 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT AG-PROTO::VALUE AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'MESSAGE)))
      (WHEN (AND AG-PROTO::VALUE (PLUSP (LENGTH AG-PROTO::VALUE)))
        (AG-PROTO::WRITE-FIELD-TAG 2 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO::STRING-TO-UTF8 AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'ECHOSTATUS)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'ECHOSTATUS))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'CODE)
                          (LET ((AG-PROTO::N
                                 (LOGAND
                                  (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)
                                  4294967295)))
                            (IF (>= AG-PROTO::N 2147483648)
                                (- AG-PROTO::N 4294967296)
                                AG-PROTO::N))))
                 (2
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'MESSAGE)
                          (AG-PROTO::UTF8-TO-STRING
                           (AG-PROTO::READ-LENGTH-DELIMITED
                            AG-PROTO::BUFFER))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS BOOLVALUE (AG-PROTO:PROTO-MESSAGE)
          ((VALUE :INITARG :VALUE :ACCESSOR VALUE :INITFORM NIL :TYPE BOOLEAN))
          (:DOCUMENTATION "Proto message: BoolValue"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES ((AG-PROTO::OBJ BOOLVALUE))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'VALUE)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 1 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT
         (IF AG-PROTO::VALUE
             1
             0)
         AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'BOOLVALUE)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'BOOLVALUE))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'VALUE)
                          (NOT
                           (ZEROP (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS SIMPLEREQUEST (AG-PROTO:PROTO-MESSAGE)
          ((RESPONSE-TYPE :INITARG :RESPONSE-TYPE :ACCESSOR RESPONSE-TYPE
            :INITFORM NIL :TYPE T)
           (RESPONSE-SIZE :INITARG :RESPONSE-SIZE :ACCESSOR RESPONSE-SIZE
            :INITFORM 0 :TYPE (SIGNED-BYTE 32))
           (PAYLOAD :INITARG :PAYLOAD :ACCESSOR PAYLOAD :INITFORM NIL :TYPE T)
           (FILL-USERNAME :INITARG :FILL-USERNAME :ACCESSOR FILL-USERNAME
            :INITFORM NIL :TYPE BOOLEAN)
           (FILL-OAUTH-SCOPE :INITARG :FILL-OAUTH-SCOPE :ACCESSOR
            FILL-OAUTH-SCOPE :INITFORM NIL :TYPE BOOLEAN)
           (RESPONSE-COMPRESSED :INITARG :RESPONSE-COMPRESSED :ACCESSOR
            RESPONSE-COMPRESSED :INITFORM NIL :TYPE T)
           (RESPONSE-STATUS :INITARG :RESPONSE-STATUS :ACCESSOR RESPONSE-STATUS
            :INITFORM NIL :TYPE T)
           (EXPECT-COMPRESSED :INITARG :EXPECT-COMPRESSED :ACCESSOR
            EXPECT-COMPRESSED :INITFORM NIL :TYPE T)
           (FILL-SERVER-ID :INITARG :FILL-SERVER-ID :ACCESSOR FILL-SERVER-ID
            :INITFORM NIL :TYPE BOOLEAN))
          (:DOCUMENTATION "Proto message: SimpleRequest"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES ((AG-PROTO::OBJ SIMPLEREQUEST))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-TYPE)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 1 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-SIZE)))
      (WHEN (AND AG-PROTO::VALUE (NOT (EQL AG-PROTO::VALUE 0)))
        (AG-PROTO::WRITE-FIELD-TAG 2 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT AG-PROTO::VALUE AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 3 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'FILL-USERNAME)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 4 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT
         (IF AG-PROTO::VALUE
             1
             0)
         AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'FILL-OAUTH-SCOPE)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 5 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT
         (IF AG-PROTO::VALUE
             1
             0)
         AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-COMPRESSED)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 6 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-STATUS)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 7 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'EXPECT-COMPRESSED)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 8 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'FILL-SERVER-ID)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 9 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT
         (IF AG-PROTO::VALUE
             1
             0)
         AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'SIMPLEREQUEST)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'SIMPLEREQUEST))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-TYPE)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOADTYPE
                                                             AG-PROTO::DATA))))
                 (2
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-SIZE)
                          (LET ((AG-PROTO::N
                                 (LOGAND
                                  (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)
                                  4294967295)))
                            (IF (>= AG-PROTO::N 2147483648)
                                (- AG-PROTO::N 4294967296)
                                AG-PROTO::N))))
                 (3
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOAD
                                                             AG-PROTO::DATA))))
                 (4
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'FILL-USERNAME)
                          (NOT
                           (ZEROP (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)))))
                 (5
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'FILL-OAUTH-SCOPE)
                          (NOT
                           (ZEROP (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)))))
                 (6
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-COMPRESSED)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'BOOLVALUE
                                                             AG-PROTO::DATA))))
                 (7
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-STATUS)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'ECHOSTATUS
                                                             AG-PROTO::DATA))))
                 (8
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'EXPECT-COMPRESSED)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'BOOLVALUE
                                                             AG-PROTO::DATA))))
                 (9
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'FILL-SERVER-ID)
                          (NOT
                           (ZEROP (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS SIMPLERESPONSE (AG-PROTO:PROTO-MESSAGE)
          ((PAYLOAD :INITARG :PAYLOAD :ACCESSOR PAYLOAD :INITFORM NIL :TYPE T)
           (USERNAME :INITARG :USERNAME :ACCESSOR USERNAME :INITFORM "" :TYPE
            STRING)
           (OAUTH-SCOPE :INITARG :OAUTH-SCOPE :ACCESSOR OAUTH-SCOPE :INITFORM
            "" :TYPE STRING)
           (SERVER-ID :INITARG :SERVER-ID :ACCESSOR SERVER-ID :INITFORM ""
            :TYPE STRING)
           (HOSTNAME :INITARG :HOSTNAME :ACCESSOR HOSTNAME :INITFORM "" :TYPE
            STRING))
          (:DOCUMENTATION "Proto message: SimpleResponse"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES ((AG-PROTO::OBJ SIMPLERESPONSE))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 1 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'USERNAME)))
      (WHEN (AND AG-PROTO::VALUE (PLUSP (LENGTH AG-PROTO::VALUE)))
        (AG-PROTO::WRITE-FIELD-TAG 2 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO::STRING-TO-UTF8 AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'OAUTH-SCOPE)))
      (WHEN (AND AG-PROTO::VALUE (PLUSP (LENGTH AG-PROTO::VALUE)))
        (AG-PROTO::WRITE-FIELD-TAG 3 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO::STRING-TO-UTF8 AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'SERVER-ID)))
      (WHEN (AND AG-PROTO::VALUE (PLUSP (LENGTH AG-PROTO::VALUE)))
        (AG-PROTO::WRITE-FIELD-TAG 4 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO::STRING-TO-UTF8 AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'HOSTNAME)))
      (WHEN (AND AG-PROTO::VALUE (PLUSP (LENGTH AG-PROTO::VALUE)))
        (AG-PROTO::WRITE-FIELD-TAG 5 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO::STRING-TO-UTF8 AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'SIMPLERESPONSE)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'SIMPLERESPONSE))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOAD
                                                             AG-PROTO::DATA))))
                 (2
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'USERNAME)
                          (AG-PROTO::UTF8-TO-STRING
                           (AG-PROTO::READ-LENGTH-DELIMITED
                            AG-PROTO::BUFFER))))
                 (3
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'OAUTH-SCOPE)
                          (AG-PROTO::UTF8-TO-STRING
                           (AG-PROTO::READ-LENGTH-DELIMITED
                            AG-PROTO::BUFFER))))
                 (4
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'SERVER-ID)
                          (AG-PROTO::UTF8-TO-STRING
                           (AG-PROTO::READ-LENGTH-DELIMITED
                            AG-PROTO::BUFFER))))
                 (5
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'HOSTNAME)
                          (AG-PROTO::UTF8-TO-STRING
                           (AG-PROTO::READ-LENGTH-DELIMITED
                            AG-PROTO::BUFFER))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS RESPONSEPARAMETERS (AG-PROTO:PROTO-MESSAGE)
          ((SIZE :INITARG :SIZE :ACCESSOR SIZE :INITFORM 0 :TYPE
            (SIGNED-BYTE 32))
           (INTERVAL-US :INITARG :INTERVAL-US :ACCESSOR INTERVAL-US :INITFORM 0
            :TYPE (SIGNED-BYTE 32))
           (COMPRESSED :INITARG :COMPRESSED :ACCESSOR COMPRESSED :INITFORM NIL
            :TYPE T))
          (:DOCUMENTATION "Proto message: ResponseParameters"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES ((AG-PROTO::OBJ RESPONSEPARAMETERS))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'SIZE)))
      (WHEN (AND AG-PROTO::VALUE (NOT (EQL AG-PROTO::VALUE 0)))
        (AG-PROTO::WRITE-FIELD-TAG 1 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT AG-PROTO::VALUE AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'INTERVAL-US)))
      (WHEN (AND AG-PROTO::VALUE (NOT (EQL AG-PROTO::VALUE 0)))
        (AG-PROTO::WRITE-FIELD-TAG 2 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT AG-PROTO::VALUE AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'COMPRESSED)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 3 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'RESPONSEPARAMETERS)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'RESPONSEPARAMETERS))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'SIZE)
                          (LET ((AG-PROTO::N
                                 (LOGAND
                                  (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)
                                  4294967295)))
                            (IF (>= AG-PROTO::N 2147483648)
                                (- AG-PROTO::N 4294967296)
                                AG-PROTO::N))))
                 (2
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'INTERVAL-US)
                          (LET ((AG-PROTO::N
                                 (LOGAND
                                  (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)
                                  4294967295)))
                            (IF (>= AG-PROTO::N 2147483648)
                                (- AG-PROTO::N 4294967296)
                                AG-PROTO::N))))
                 (3
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'COMPRESSED)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'BOOLVALUE
                                                             AG-PROTO::DATA))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS STREAMINGOUTPUTCALLREQUEST (AG-PROTO:PROTO-MESSAGE)
          ((RESPONSE-TYPE :INITARG :RESPONSE-TYPE :ACCESSOR RESPONSE-TYPE
            :INITFORM NIL :TYPE T)
           (RESPONSE-PARAMETERS :INITARG :RESPONSE-PARAMETERS :ACCESSOR
            RESPONSE-PARAMETERS :INITFORM NIL :TYPE LIST)
           (PAYLOAD :INITARG :PAYLOAD :ACCESSOR PAYLOAD :INITFORM NIL :TYPE T)
           (RESPONSE-STATUS :INITARG :RESPONSE-STATUS :ACCESSOR RESPONSE-STATUS
            :INITFORM NIL :TYPE T))
          (:DOCUMENTATION "Proto message: StreamingOutputCallRequest"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES
           ((AG-PROTO::OBJ STREAMINGOUTPUTCALLREQUEST))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-TYPE)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 1 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (DOLIST (AG-PROTO::ELEM (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-PARAMETERS))
      (AG-PROTO::WRITE-FIELD-TAG 2 2 AG-PROTO::BUFFER)
      (AG-PROTO::WRITE-LENGTH-DELIMITED
       (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::ELEM) AG-PROTO::BUFFER))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 3 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-STATUS)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 7 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'STREAMINGOUTPUTCALLREQUEST)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'STREAMINGOUTPUTCALLREQUEST))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-TYPE)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOADTYPE
                                                             AG-PROTO::DATA))))
                 (2
                  (PUSH
                   (LET ((AG-PROTO::DATA
                          (AG-PROTO::READ-LENGTH-DELIMITED AG-PROTO::BUFFER)))
                     (AG-PROTO:DESERIALIZE-FROM-BYTES 'RESPONSEPARAMETERS
                                                      AG-PROTO::DATA))
                   (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-PARAMETERS)))
                 (3
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOAD
                                                             AG-PROTO::DATA))))
                 (7
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-STATUS)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'ECHOSTATUS
                                                             AG-PROTO::DATA))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    (SETF (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-PARAMETERS)
            (NREVERSE (SLOT-VALUE AG-PROTO::OBJ 'RESPONSE-PARAMETERS)))
    AG-PROTO::OBJ))


(DEFCLASS STREAMINGOUTPUTCALLRESPONSE (AG-PROTO:PROTO-MESSAGE)
          ((PAYLOAD :INITARG :PAYLOAD :ACCESSOR PAYLOAD :INITFORM NIL :TYPE T))
          (:DOCUMENTATION "Proto message: StreamingOutputCallResponse"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES
           ((AG-PROTO::OBJ STREAMINGOUTPUTCALLRESPONSE))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 1 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'STREAMINGOUTPUTCALLRESPONSE)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'STREAMINGOUTPUTCALLRESPONSE))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOAD
                                                             AG-PROTO::DATA))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS STREAMINGINPUTCALLREQUEST (AG-PROTO:PROTO-MESSAGE)
          ((PAYLOAD :INITARG :PAYLOAD :ACCESSOR PAYLOAD :INITFORM NIL :TYPE T)
           (EXPECT-COMPRESSED :INITARG :EXPECT-COMPRESSED :ACCESSOR
            EXPECT-COMPRESSED :INITFORM NIL :TYPE T))
          (:DOCUMENTATION "Proto message: StreamingInputCallRequest"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES
           ((AG-PROTO::OBJ STREAMINGINPUTCALLREQUEST))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 1 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'EXPECT-COMPRESSED)))
      (WHEN AG-PROTO::VALUE
        (AG-PROTO::WRITE-FIELD-TAG 2 2 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-LENGTH-DELIMITED
         (AG-PROTO:SERIALIZE-TO-BYTES AG-PROTO::VALUE) AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'STREAMINGINPUTCALLREQUEST)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'STREAMINGINPUTCALLREQUEST))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'PAYLOAD)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'PAYLOAD
                                                             AG-PROTO::DATA))))
                 (2
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'EXPECT-COMPRESSED)
                          (LET ((AG-PROTO::DATA
                                 (AG-PROTO::READ-LENGTH-DELIMITED
                                  AG-PROTO::BUFFER)))
                            (AG-PROTO:DESERIALIZE-FROM-BYTES 'BOOLVALUE
                                                             AG-PROTO::DATA))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS STREAMINGINPUTCALLRESPONSE (AG-PROTO:PROTO-MESSAGE)
          ((AGGREGATED-PAYLOAD-SIZE :INITARG :AGGREGATED-PAYLOAD-SIZE :ACCESSOR
            AGGREGATED-PAYLOAD-SIZE :INITFORM 0 :TYPE (SIGNED-BYTE 32)))
          (:DOCUMENTATION "Proto message: StreamingInputCallResponse"))


(DEFMETHOD AG-PROTO:SERIALIZE-TO-BYTES
           ((AG-PROTO::OBJ STREAMINGINPUTCALLRESPONSE))
  (LET ((AG-PROTO::BUFFER
         (MAKE-ARRAY 64 :ELEMENT-TYPE '(UNSIGNED-BYTE 8) :FILL-POINTER 0
                     :ADJUSTABLE T)))
    (LET ((AG-PROTO::VALUE (SLOT-VALUE AG-PROTO::OBJ 'AGGREGATED-PAYLOAD-SIZE)))
      (WHEN (AND AG-PROTO::VALUE (NOT (EQL AG-PROTO::VALUE 0)))
        (AG-PROTO::WRITE-FIELD-TAG 1 0 AG-PROTO::BUFFER)
        (AG-PROTO::WRITE-VARINT AG-PROTO::VALUE AG-PROTO::BUFFER)))
    AG-PROTO::BUFFER))


(DEFMETHOD AG-PROTO:DESERIALIZE-FROM-BYTES
           ((TYPE (EQL 'STREAMINGINPUTCALLRESPONSE)) AG-PROTO::DATA)
  (LET ((AG-PROTO::OBJ (MAKE-INSTANCE 'STREAMINGINPUTCALLRESPONSE))
        (AG-PROTO::BUFFER (CONS AG-PROTO::DATA 0)))
    (LOOP AG-PROTO::WHILE (< (CDR AG-PROTO::BUFFER) (LENGTH AG-PROTO::DATA))
          DO (LET* ((AG-PROTO::TAG (AG-PROTO::READ-VARINT AG-PROTO::BUFFER))
                    (AG-PROTO::FIELD-NUMBER (ASH AG-PROTO::TAG -3))
                    (AG-PROTO::WIRE-TYPE (LOGAND AG-PROTO::TAG 7)))
               (CASE AG-PROTO::FIELD-NUMBER
                 (1
                  (SETF (SLOT-VALUE AG-PROTO::OBJ 'AGGREGATED-PAYLOAD-SIZE)
                          (LET ((AG-PROTO::N
                                 (LOGAND
                                  (AG-PROTO::READ-VARINT AG-PROTO::BUFFER)
                                  4294967295)))
                            (IF (>= AG-PROTO::N 2147483648)
                                (- AG-PROTO::N 4294967296)
                                AG-PROTO::N))))
                 (OTHERWISE
                  (AG-PROTO::SKIP-FIELD AG-PROTO::BUFFER
                                        AG-PROTO::WIRE-TYPE)))))
    AG-PROTO::OBJ))


(DEFCLASS TEST-SERVICE-STUB NIL
          ((AG-PROTO::CHANNEL :INITARG :CHANNEL :ACCESSOR AG-PROTO:STUB-CHANNEL
            :DOCUMENTATION "gRPC channel for this stub"))
          (:DOCUMENTATION "Client stub for TestService service"))


(DEFUN MAKE-TEST-SERVICE-STUB (AG-PROTO::CHANNEL)
  "Create a new TestService client stub"
  (MAKE-INSTANCE 'TEST-SERVICE-STUB :CHANNEL AG-PROTO::CHANNEL))


(DEFMETHOD TEST-SERVICE-EMPTY-CALL
           ((AG-PROTO::STUB TEST-SERVICE-STUB) AG-PROTO::REQUEST
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Call TestService.EmptyCall unary RPC"
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-UNARY" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::RESPONSE-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-RESPONSE" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::STATUS-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-STATUS" AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (LET ((AG-PROTO::CALL
           (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
                    "/grpc.testing.TestService/EmptyCall" AG-PROTO::REQUEST
                    :RESPONSE-TYPE 'EMPTY :METADATA AG-PROTO::METADATA :TIMEOUT
                    AG-PROTO::TIMEOUT)))
      (VALUES (FUNCALL AG-PROTO::RESPONSE-FN AG-PROTO::CALL)
              (FUNCALL AG-PROTO::STATUS-FN AG-PROTO::CALL) AG-PROTO::CALL))))


(DEFMETHOD TEST-SERVICE-UNARY-CALL
           ((AG-PROTO::STUB TEST-SERVICE-STUB) AG-PROTO::REQUEST
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Call TestService.UnaryCall unary RPC"
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-UNARY" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::RESPONSE-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-RESPONSE" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::STATUS-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-STATUS" AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (LET ((AG-PROTO::CALL
           (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
                    "/grpc.testing.TestService/UnaryCall" AG-PROTO::REQUEST
                    :RESPONSE-TYPE 'SIMPLERESPONSE :METADATA AG-PROTO::METADATA
                    :TIMEOUT AG-PROTO::TIMEOUT)))
      (VALUES (FUNCALL AG-PROTO::RESPONSE-FN AG-PROTO::CALL)
              (FUNCALL AG-PROTO::STATUS-FN AG-PROTO::CALL) AG-PROTO::CALL))))


(DEFMETHOD TEST-SERVICE-STREAMING-OUTPUT-CALL
           ((AG-PROTO::STUB TEST-SERVICE-STUB) AG-PROTO::REQUEST
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Call TestService.StreamingOutputCall server streaming RPC.
Returns a grpc-server-stream. Use stream-read-message or do-stream-messages to consume."
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-SERVER-STREAMING" AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
             "/grpc.testing.TestService/StreamingOutputCall" AG-PROTO::REQUEST
             :RESPONSE-TYPE 'STREAMINGOUTPUTCALLRESPONSE :METADATA
             AG-PROTO::METADATA :TIMEOUT AG-PROTO::TIMEOUT)))


(DEFMETHOD TEST-SERVICE-STREAMING-INPUT-CALL
           ((AG-PROTO::STUB TEST-SERVICE-STUB)
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Initiate TestService.StreamingInputCall client streaming RPC.
Returns a grpc-client-stream. Use stream-send to send messages,
then stream-close-and-recv to get the response."
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-CLIENT-STREAMING" AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
             "/grpc.testing.TestService/StreamingInputCall" :RESPONSE-TYPE
             'STREAMINGINPUTCALLRESPONSE :METADATA AG-PROTO::METADATA :TIMEOUT
             AG-PROTO::TIMEOUT)))


(DEFMETHOD TEST-SERVICE-FULL-DUPLEX-CALL
           ((AG-PROTO::STUB TEST-SERVICE-STUB)
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Initiate TestService.FullDuplexCall bidirectional streaming RPC.
Returns a grpc-bidi-stream. Use stream-send to send messages,
stream-read-message to receive messages, and stream-close-send when done sending."
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-BIDIRECTIONAL-STREAMING"
                             AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
             "/grpc.testing.TestService/FullDuplexCall" :RESPONSE-TYPE
             'STREAMINGOUTPUTCALLRESPONSE :METADATA AG-PROTO::METADATA :TIMEOUT
             AG-PROTO::TIMEOUT)))


(DEFMETHOD TEST-SERVICE-HALF-DUPLEX-CALL
           ((AG-PROTO::STUB TEST-SERVICE-STUB)
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Initiate TestService.HalfDuplexCall bidirectional streaming RPC.
Returns a grpc-bidi-stream. Use stream-send to send messages,
stream-read-message to receive messages, and stream-close-send when done sending."
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-BIDIRECTIONAL-STREAMING"
                             AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
             "/grpc.testing.TestService/HalfDuplexCall" :RESPONSE-TYPE
             'STREAMINGOUTPUTCALLRESPONSE :METADATA AG-PROTO::METADATA :TIMEOUT
             AG-PROTO::TIMEOUT)))


(DEFMETHOD TEST-SERVICE-UNIMPLEMENTED-CALL
           ((AG-PROTO::STUB TEST-SERVICE-STUB) AG-PROTO::REQUEST
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Call TestService.UnimplementedCall unary RPC"
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-UNARY" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::RESPONSE-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-RESPONSE" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::STATUS-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-STATUS" AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (LET ((AG-PROTO::CALL
           (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
                    "/grpc.testing.TestService/UnimplementedCall"
                    AG-PROTO::REQUEST :RESPONSE-TYPE 'EMPTY :METADATA
                    AG-PROTO::METADATA :TIMEOUT AG-PROTO::TIMEOUT)))
      (VALUES (FUNCALL AG-PROTO::RESPONSE-FN AG-PROTO::CALL)
              (FUNCALL AG-PROTO::STATUS-FN AG-PROTO::CALL) AG-PROTO::CALL))))


(DEFCLASS UNIMPLEMENTED-SERVICE-STUB NIL
          ((AG-PROTO::CHANNEL :INITARG :CHANNEL :ACCESSOR AG-PROTO:STUB-CHANNEL
            :DOCUMENTATION "gRPC channel for this stub"))
          (:DOCUMENTATION "Client stub for UnimplementedService service"))


(DEFUN MAKE-UNIMPLEMENTED-SERVICE-STUB (AG-PROTO::CHANNEL)
  "Create a new UnimplementedService client stub"
  (MAKE-INSTANCE 'UNIMPLEMENTED-SERVICE-STUB :CHANNEL AG-PROTO::CHANNEL))


(DEFMETHOD UNIMPLEMENTED-SERVICE-UNIMPLEMENTED-CALL
           ((AG-PROTO::STUB UNIMPLEMENTED-SERVICE-STUB) AG-PROTO::REQUEST
            &KEY AG-PROTO::METADATA AG-PROTO::TIMEOUT)
  "Call UnimplementedService.UnimplementedCall unary RPC"
  (LET* ((AG-PROTO::GRPC-PKG (FIND-PACKAGE :AG-GRPC))
         (AG-PROTO::CALL-FN
          (AND AG-PROTO::GRPC-PKG
               (SYMBOL-FUNCTION
                (FIND-SYMBOL "CALL-UNARY" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::RESPONSE-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-RESPONSE" AG-PROTO::GRPC-PKG))))
         (AG-PROTO::STATUS-FN
          (AND AG-PROTO::GRPC-PKG
               (FDEFINITION (FIND-SYMBOL "CALL-STATUS" AG-PROTO::GRPC-PKG)))))
    (UNLESS AG-PROTO::CALL-FN
      (ERROR
       "ag-grpc package not loaded. Load ag-grpc before calling RPC methods."))
    (LET ((AG-PROTO::CALL
           (FUNCALL AG-PROTO::CALL-FN (AG-PROTO:STUB-CHANNEL AG-PROTO::STUB)
                    "/grpc.testing.UnimplementedService/UnimplementedCall"
                    AG-PROTO::REQUEST :RESPONSE-TYPE 'EMPTY :METADATA
                    AG-PROTO::METADATA :TIMEOUT AG-PROTO::TIMEOUT)))
      (VALUES (FUNCALL AG-PROTO::RESPONSE-FN AG-PROTO::CALL)
              (FUNCALL AG-PROTO::STATUS-FN AG-PROTO::CALL) AG-PROTO::CALL))))

