;;;; main.lisp - CLI entry point for ag-proto
;;;
;;; SPDX-License-Identifier: MIT

(in-package #:ag-proto-cli)

(version-string:define-version-parameter +version+ :ag-proto-cli)

;;; -------------------------------------------------------------------------
;;; CLI Options
;;; -------------------------------------------------------------------------

(defun make-output-option ()
  "Create -o/--output option for specifying output file."
  (clingon:make-option
   :string
   :short-name #\o
   :long-name "output"
   :key :output
   :description "Output file path (default: stdout)"))

(defun make-output-dir-option ()
  "Create --output-dir option for specifying output directory."
  (clingon:make-option
   :string
   :long-name "output-dir"
   :key :output-dir
   :description "Output directory (derives filename from input)"))

(defun make-package-option ()
  "Create -p/--package option for specifying target package."
  (clingon:make-option
   :string
   :short-name #\p
   :long-name "package"
   :key :package
   :description "Target Common Lisp package (default: CL-USER)"))

(defun make-load-option ()
  "Create -l/--load option for loading generated code."
  (clingon:make-option
   :flag
   :short-name #\l
   :long-name "load"
   :key :load
   :description "Load generated code after compilation"))

(defun make-print-option ()
  "Create --print option for printing generated code."
  (clingon:make-option
   :flag
   :long-name "print"
   :key :print
   :description "Print generated code to stdout"))

(defun make-verbose-option ()
  "Create -v/--verbose option for verbose output."
  (clingon:make-option
   :flag
   :short-name #\v
   :long-name "verbose"
   :key :verbose
   :description "Show verbose output"))

;;; -------------------------------------------------------------------------
;;; CLI Handler
;;; -------------------------------------------------------------------------

(defun derive-output-filename (input-path output-dir)
  "Derive output filename from input path and output directory."
  (let* ((name (pathname-name input-path))
         (output-name (format nil "~A.lisp" name)))
    (if output-dir
        (merge-pathnames output-name (pathname output-dir))
        output-name)))

(defun compile-proto-to-lisp (input-file &key output-file package load verbose print)
  "Compile a single .proto file to Lisp."
  (when verbose
    (format *error-output* "; Compiling ~A~%" input-file))
  (let* ((pkg (if package
                  (or (find-package (string-upcase package))
                      (make-package (string-upcase package)))
                  (find-package :cl-user)))
         (file-desc (ag-proto:parse-proto-file input-file))
         (forms (ag-proto:generate-lisp-code file-desc :package pkg)))
    ;; Write to output file if specified
    (when output-file
      (when verbose
        (format *error-output* "; Writing to ~A~%" output-file))
      (with-open-file (out output-file
                           :direction :output
                           :if-exists :supersede)
        (format out ";;;; Generated from ~A~%~%" input-file)
        (format out ";;;; Generated by ag-proto-cli v~A~%~%" +version+)
        (format out "(in-package ~S)~%~%" (package-name pkg))
        (dolist (form forms)
          (pprint form out)
          (terpri out)
          (terpri out))))
    ;; Print to stdout if requested
    (when print
      (format t ";;;; Generated from ~A~%~%" input-file)
      (format t "(in-package ~S)~%~%" (package-name pkg))
      (dolist (form forms)
        (pprint form *standard-output*)
        (terpri)
        (terpri)))
    ;; Load if requested
    (when load
      (when verbose
        (format *error-output* "; Loading generated code~%"))
      (dolist (form forms)
        (eval form)))
    (when verbose
      (format *error-output* "; Generated ~D forms~%" (length forms)))
    forms))

(defun handle-cli (cmd)
  "Handle CLI command execution."
  (let ((output-file (clingon:getopt cmd :output))
        (output-dir (clingon:getopt cmd :output-dir))
        (package (clingon:getopt cmd :package))
        (load (clingon:getopt cmd :load))
        (print (clingon:getopt cmd :print))
        (verbose (clingon:getopt cmd :verbose))
        (args (clingon:command-arguments cmd)))
    ;; Validate arguments
    (unless args
      (format *error-output* "Error: No input files specified~%")
      (format *error-output* "Usage: ag-protoc [options] file.proto ...~%")
      (uiop:quit 1))
    (when (and output-file (cdr args))
      (format *error-output* "Error: Cannot use -o with multiple input files~%")
      (format *error-output* "Use --output-dir instead~%")
      (uiop:quit 1))
    ;; Create output directory if needed
    (when output-dir
      (ensure-directories-exist (merge-pathnames "x" (pathname output-dir))))
    ;; If no output specified and not printing, default to print
    (when (and (not output-file) (not output-dir) (not print) (not load))
      (setf print t))
    ;; Process each input file
    (handler-case
        (dolist (input-file args)
          (let ((out-file (cond
                            (output-file output-file)
                            (output-dir (derive-output-filename input-file output-dir))
                            (t nil))))
            (compile-proto-to-lisp input-file
                                   :output-file out-file
                                   :package package
                                   :load load
                                   :verbose verbose
                                   :print print)))
      (error (e)
        (format *error-output* "Error: ~A~%" e)
        (uiop:quit 1)))))

;;; -------------------------------------------------------------------------
;;; CLI Application
;;; -------------------------------------------------------------------------

(defun make-app ()
  "Create the ag-proto CLI application."
  (clingon:make-command
   :name "ag-protoc"
   :version +version+
   :description "Generate Common Lisp code from Protocol Buffer files"
   :long-description "ag-protoc compiles .proto files to Common Lisp code.

The generated code includes:
- CLOS class definitions for each proto message
- serialize-to-bytes method for each message
- deserialize-from-bytes method for each message
- Constants for enum values

Examples:
  ag-protoc --print example.proto
  ag-protoc -o example.lisp example.proto
  ag-protoc --output-dir generated/ *.proto
  ag-protoc -p my-app --load example.proto"
   :authors '("Anthony Green <green@moxielogic.com>")
   :license "MIT"
   :usage "[options] file.proto ..."
   :options (list (make-output-option)
                  (make-output-dir-option)
                  (make-package-option)
                  (make-load-option)
                  (make-print-option)
                  (make-verbose-option))
   :handler #'handle-cli))

;;; -------------------------------------------------------------------------
;;; Entry Point
;;; -------------------------------------------------------------------------

(defun main ()
  "The main entry point for ag-proto-cli."
  (handler-case
      (clingon:run (make-app))
    (error (e)
      (format *error-output* "Fatal error: ~A~%" e)
      (uiop:quit 1))))
